gamespace/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
  path("main/", include("main.urls")),
  path('accounts/', include('django.contrib.auth.urls')),
  path('admin/', admin.site.urls),
]

handler404 = 'main.views.handler404'
handler403 = 'main.views.handler403'

main/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
#add the view to urlpatterns
app_name= "main"
urlpatterns = [
  path("",views.listing, name = "game"),
  path("register/", views.register,name="register"),
  path("create/", views.CreateGame.as_view(),name="create"),
  path("profile/", views.Profile.as_view(),name="profile"),
  path("game_overview/<int:pk>/",views.GameOverview.as_view(),name="game_overview"),
  path("join_request/<int:pk>/", views.JoinRequest.as_view(),name="join_request"),
  path("pending_chars/<int:pk>/", views.Pending.as_view() ,name="pending_characters"),
  path("remove_player/<int:pk>/", views.Remove.as_view() ,name="remove_player"),
  path("edit_game/<int:pk>/", views.EditGame.as_view(), name="edit_game"),
  path("create_character/",views.CreateCharacter.as_view(),name="create_character"),
  path("profile/edit/<int:pk>/",views.EditProfile.as_view(),name="edit"),
  path("delete_game/<int:pk>/", views.DeleteGame.as_view() ,name="delete_game"),
  path("delete_player/<int:pk>/", views.DeletePlayer.as_view() ,name="delete_player"),
  path("delete_character/<int:pk>/",views.DeleteCharacter.as_view(),name="delete_character"),
]

main/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# this is where our databases are setup (I think)
# helpfull list of Fields https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.CharField


class UserProfile(models.Model):
    objects = models.Manager()

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    v_name = models.CharField(max_length=32)
    bio = models.CharField(max_length=512, default="A new adventurer ")
    join_date = models.DateTimeField("date joined", default=timezone.now)
    email = models.EmailField(max_length=254)
    picture = models.ImageField(
        upload_to=None, height_field=None, width_field=None, max_length=100)


    def get_bio(self):
        return self.bio

    def __str__(self):
        return self.v_name

    def update_profile(self, up):
      self.v_name = up.v_name
      self.bio = up.bio
      self.save()



class Game(models.Model):
    objects = models.Manager()

    game_master = models.ForeignKey(
        UserProfile, related_name="game_master", null=True, on_delete=models.CASCADE)

    created_at = models.DateTimeField("date created", default=timezone.now)
    name = models.CharField(max_length=64, default="A super cool adventure")
    desc = models.CharField(max_length=1024, default="")
    ruleset = models.CharField(max_length=64, default="")
    ESRB = models.CharField(max_length=16, default="Exactly 3 years old")
    location = models.CharField(max_length=256, default="SPACE")
    max_players = models.IntegerField(default=4)
    int_current_players = models.IntegerField(default=0)
    num_encounters = models.IntegerField(default=5)
    # who want's pictures for the games too?

    players = models.ManyToManyField(UserProfile, related_name="in_games")
    pending_players = models.ManyToManyField(
        UserProfile, related_name="pending_players")

    def get_desc(self):
        return self.desc

    def __str__(self):
        return self.name
    
    def update_game(self, game):
        self.name = game.name
        self.desc = game.desc
        self.ruleset = game.ruleset
        self.ESRB = game.ESRB
        self.location = game.location
        self.max_players = game.max_players
        self.num_encounters = game.num_encounters
        self.save()

    def is_equal(self, game):
        if not(self.name == game.name):
            return False
        if not(self.desc == game.desc):
            return False
        if not(self.ruleset == game.ruleset):
            return False
        if not(self.ESRB == game.ESRB):
            return False
        if not(self.location == game.location):
            return False
        if not(self.max_players == game.max_players):
            return False
        if not(self.num_encounters == game.num_encounters):
            return False

class Character(models.Model):
    objects = models.Manager()

    owner = models.ForeignKey(UserProfile, related_name="user_character_set",null=True, on_delete=models.CASCADE)
    associated_game = models.ForeignKey(Game,related_name="game_character_set",on_delete=models.CASCADE)
    name = models.CharField(max_length= 64)
    bio = models.CharField(max_length= 512)
    # when we get to uploading pdfs a fileField may be usefull
    characterSheet = models.ImageField(
        upload_to=None, height_field=None, width_field=None, max_length=100)
    hasButt = models.BooleanField(default=True)

    def update_character(self, character):
        self.name = character.name
        self.bio = character.bio
        self.save()

    def set_butt(self, bool):
      self.hasButt=bool

main/forms.py
from django import forms
from main.models import UserProfile, Game
from django.contrib.auth.models import User

#django authentication for username and password
class CreateUserForm(forms.ModelForm):
  #this formats the password to do the auto hide thing
  password = forms.CharField(widget=forms.PasswordInput())

  #the class meta provides the minimum for the form 
  class Meta:
    model = User
    #will add email in iteration 2 if we decide to have email enabled
    fields = ("username","password")

#form fields specific to out project
class CreateUserProfileForm(forms.ModelForm):
  class Meta:
    model = UserProfile
    fields = ("v_name",)

main/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic, View
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.contrib.auth import login, logout
from django.template import RequestContext
from django.utils import timezone
from django import template

from .models import UserProfile, Game, Character
from main.forms import CreateUserForm, CreateUserProfileForm

#----------------
# Main pages
#----------------

def listing(request):
  obj_list = Game.objects.order_by('-created_at')
  paginator = Paginator(obj_list,5)

  page = request.GET.get('page')
  games=paginator.get_page(page)
  return render(request,"main/index.html",{"games":games})

  
class Login(CreateView):
  template_name = "accounts/login.html"
  CreateView.model = UserProfile
  fields = '__all__'
  success_url="/main"


class Profile(TemplateView):
  template_name = "main/profile.html"


class GameOverview(generic.DetailView):
  model = Game
  context_object_name="game"
  template_name="main/game_overview.html"


#----------------
# Create views
#----------------
class CreateGame(CreateView):
  template_name = "main/create_game.html"
  CreateView.model = Game
  fields="name","desc","max_players","ruleset","ESRB","location","num_encounters"
  success_url="/main"
  def form_valid(self, form):
    game=form.save(commit=False)
    game.game_master = self.request.user.userprofile
    self.object=game
    self.object.save()
    return HttpResponseRedirect(self.get_success_url())

def register(request):
  context = RequestContext(request)
  registered = False
  if request.method=="POST":
    user_form = CreateUserForm(data=request.POST)
    profile_form = CreateUserProfileForm(data=request.POST)

    if user_form.is_valid() and profile_form.is_valid():
      user=user_form.save()

      #the set_password function hashes our password
      user.set_password(user.password)
      user.save()

      profile = profile_form.save(commit=False)
      profile.user = user
      profile.save()

      registered = True
      return HttpResponseRedirect("/accounts/login/",context)
  else:
    user_form = CreateUserForm()
    profile_form = CreateUserProfileForm()
    
  return render_to_response("main/register.html", {"user_form":user_form, "profile_form":profile_form,"registered":registered}, context)


#----------------
# Edit views
#----------------
class EditGame(UpdateView):
  template_name = "main/edit_game.html"
  model = Game
  fields="name","desc","max_players","ruleset","ESRB","location","num_encounters"

  def form_valid(self, form):
    if self.request.user.userprofile==self.object.game_master:
      game=form.save(commit=False)
      self.object.update_game(game)
      return HttpResponseRedirect("/main/game_overview/" + str(self.object.id))

class EditProfile(UpdateView):
  template_name = "main/edit_profile.html"
  model = UserProfile
  fields="v_name","bio",

  def form_valid(self,form):
    if self.request.user.userprofile==self.object:
      up=form.save(commit=False)
      self.object.update_profile(up)
      return HttpResponseRedirect("/main/profile/")



#class EditCharacter(UpdateView):
    

#----------------
# Tags
#----------------
class RequestView(generic.DetailView):
  template_name = "main/request.html"
  model = Game
  context_object_name = "game"
     
class Pending(UpdateView):
  template_name = "tags/pending_chars.html" # these are needed for form processing
  fields=["players",]
  model = Game
  def form_valid(self,form):
    state=self.request.POST.__getitem__("submit")
    if state=="Create":
      for p in self.request.POST.getlist("players"):
        u=UserProfile.objects.get(id=p)
        self.object.players.add(u)
        self.object.pending_players.remove(u)
        self.object.int_current_players+=1
        self.object.save()
    if state =="Destroy":
      for p in self.request.POST.getlist("players"):
        self.object.pending_players.remove(UserProfile.objects.get(id=p))
        self.object.save()
    return HttpResponseRedirect("/main/game_overview/" + str(self.object.id)) #this is how to redirect to same page

#handles removing user from game, inserted into game_overview
class Remove(UpdateView):
  template_name = "tags/remove_player.html" # these are needed for form processing
  fields=["players",]
  model = Game
  def form_valid(self,form):
    if (self.request.user.userprofile == self.object.game_master):
      for p in self.request.POST.getlist("players"):
        u=UserProfile.objects.get(id=p) # finds the user with the pending id
        self.object.players.remove(u) #removes that user from the game's players
        self.object.int_current_players-=1
        self.object.save()
      return HttpResponseRedirect("/main/game_overview/" + str(self.object.id)) #this is how to redirect to same page
    else:
      response = render_to_response("/error_codes/403.html")
      response.status_code = 403
      return response

class DeleteGame(DeleteView):
  template_name="tags/delete_game.html"
  fields=[]
  model = Game
  success_url="/main/"
  def form_valid(self,form):
    if (self.request.user.userprofile == self.object.game_master):
      self.object.delete()
      return HttpResponseRedirect(self.get_success_url())

class DeletePlayer(UpdateView):
  template_name="tags/delete_game.html"
  fields=[]
  model=UserProfile
  success_url="/main/"
  def form_valid(self,form):
      u = UserProfile.objects.get(id=self.request.user.id).user
      u.is_active=False
      u.delete()
      return HttpResponseRedirect(self.get_success_url())

class DeleteCharacter(DeleteView):
  template_name="tags/delete_character.html"
  fields=[]
  model = Character
  success_url="/main/profile/"
  def form_valid(self,form):
    if (self.request.user.userprofile == self.object.owner):
      self.object.delete()
      return HttpResponseRedirect(self.get_success_url())


class JoinRequest(UpdateView):
  template_name = "tags/request.html"
  model = Game
  fields=[]
  success_url="/main"
  def form_valid(self,form):

    game=self.object
    up=self.request.user.userprofile
    if up not in game.players.all():#guard
      game.pending_players.add(up)
      game.save()
    return HttpResponseRedirect(self.get_success_url())


class CreateCharacter(CreateView):
  template_name = "tags/create_character.html"
  fields=["name","bio","associated_game"]
  model = Character
  def form_valid(self,form):
    print("\n\nVALID\n\n")
    character=form.save(commit=False)
    character.owner = self.request.user.userprofile
    self.object=character
    self.object.save()
    return HttpResponseRedirect("/main/profile")
  def form_invalid(self,form):
    print("\n\nINVALID\n\n")
    for p in form:
      print(str(p))
      print("\n")
    return HttpResponseRedirect("/main/profile")

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>gamespace</title>
  <meta charset="utf-8" />
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
  <link rel="icon" 
      type="image/png" 
      href="{%static 'logo.png'%}">
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-default">
    <div class="container-fluid">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">

        <!-- Button that toggles the navbar on and off on small screens -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar"
          aria-expanded="false">

          <!-- Hides information from screen readers -->
          <span class="sr-only"></span>

          <!-- Draws 4 bars in navbar button when in small mode -->
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>

          
        </button>

        
        <img src="{%static 'logo.png'%}" alt="logo.pong" class="image-fluid" id="logo">
      </div>

      
      <div class="collapse navbar-collapse"  id="top-navbar">
        <ul class="nav navbar-nav" data-toggle="collapse" data-target="navbar-collapse">
          {% if user.is_authenticated %}
          <li class="nav-item profile_logoutt"><a href="{% url 'logout' %}">Log out</a></li>
          <li class="nav-item overview"><a href="/main/">Overview</a></li>
          <li class="nav-item profile"><a href="/main/profile">Profile</a></li>
          <li class="nav-item create"><a href="/main/create">Create a Game</a></li>
          
          {%else%}
          <li class="Signup Joined_games"><a href="/main/register">Sign Up</a></li>
          <li class="Overview"><a href="/main/">Overview</a></li>
          <li class="Profile Loginn"><a href="{% url 'login' %}">Log in</a></li>
          {%endif%}
        </ul>
        
        <div class="name align-middle pull-right" >{{ user.userprofile.v_name }}</div>
      </div>
    </div>
  </nav>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
<div class=biggie>
  {%block content%} {%endblock%}
</div>

</html>

main/templates/main/create_game.html
{% extends "main/base.html" %}

{% block content %}
{% if user.is_authenticated %}
{% if form.errors %}
<p class="warning">{{ form.errors }}</p>
{% endif %}
<form id="create-game" method="POST" action="/main/create/">
  <div class="container">
    <div class="well">
      <h2 class="text-center">Create Game</h2>
      <div class="form-group">
        <label for="id_name">Game Name:</label>
        <input placeholder="Name" class="form-control" type="text" name="name" maxlength="64" required id="id_name">
      </div>
      <div class="form-group">
        <label for="id_desc">Game Description:</label>
        <textarea rows = 6 placeholder="Description" class="form-control" name="desc" maxlength="1024" required id="id_desc"></textarea>
      </div>
      <div class="form-group">
        <label for="id_ruleset">Ruleset:</label>
        <input placeholder="Ruleset" class="form-control" type="text" name="ruleset" maxlength="64" required id="id_ruleset">
      </div>
      <div class="form-group">
        <label for="id_ESRB">Rating:</label>
        <input placeholder="ESRB" class="form-control" type="text" name="ESRB" maxlength="16" required id="id_ESRB">
      </div>
      <div class="form-group">
        <label for="id_location">Location:</label>
        <input placeholder="Location" class="form-control" type="text" name="location" maxlength="256" required id="id_location">
      </div>
      <div class="form-group">
        <label for="id_max_players">Maximum Players:</label>
        <input placeholder="Max Players" class="form-control" type="text" name="max_players" maxlength="1024" required id="id_max_players">
      </div>
      <div class="form-group">
          <label for="id_num_encounters">Number of Encounters:</label>
        <input placeholder="Number of Encounters" class="form-control" type="text" name="num_encounters" maxlength="1024" required id="id_num_encounters">
      </div>
      {% csrf_token %}
      <button type="submit" class="btn pull-right" name="submit" value="Create">Create Game</button>
      <p>&nbsp;</p>
    </div>
  </div>
</form>
{% else %}
<div class="well">
  <h1>You must be logged in to create a game</h1>
  <a class="btn" href="/accounts/login">Login</a>
<div>
{% endif %}
{% endblock %}

main/templates/main/edit_game.html
{% extends "main/base.html" %}

{% block content %}
  {% if user.is_authenticated and user.userprofile == game.game_master %}
  {% if form.errors %}
  <p class="warning">{{ form.errors }}</p>
  {% endif %}
  <form id="edit-game" method="POST" action="{% url 'main:edit_game' game.id %}">
    <div class="container">
      <div class="well">
        <h2 class="text-center">Edit Game</h2>
        <div class="form-group">
            <div class="form-group">
              <label for="id_name">Game Name:</label>
              <input placeholder="Name" class="form-control" type="text" name="name" maxlength="64" required id="id_name" value="{{game.name}}"/>
            </div>
            <div class="form-group">
              <label for="id_desc">Game Description:</label>
              <textarea rows = 6 placeholder="Description" class="form-control" name="desc" maxlength="1024" required id="id_desc">{{game.desc}}</textarea>
            </div>
            <div class="form-group">
              <label for="id_ruleset">Ruleset:</label>
              <input placeholder="Ruleset" class="form-control" type="text" name="ruleset" maxlength="64" required id="id_ruleset" value="{{game.ruleset}}"/>
            </div>
            <div class="form-group">
              <label for="id_ESRB">Rating:</label>
              <input placeholder="ESRB" class="form-control" type="text" name="ESRB" maxlength="16" required id="id_ESRB" value="{{game.ESRB}}"/>
            </div>
            <div class="form-group">
              <label for="id_location">Location:</label>        
              <input placeholder="Location" class="form-control" type="text" name="location" maxlength="256" required id="id_location" value="{{game.location}}"/>
            </div>
            <div class="form-group">
              <label for="id_max_players">Maximum Players:</label>
              <input placeholder="Max Players" class="form-control" type="text" name="max_players" maxlength="1024" required id="id_max_players" value="{{game.max_players}}"/>
            </div>
            <div class="form-group">
              <label for="id_num_encounters">Number of Encounters:</label>
              <input placeholder="Number of Encounters" class="form-control" type="text" name="num_encounters" maxlength="1024" required id="id_num_encounters" value="{{game.num_encounters}}"/>
            </div>
            {% csrf_token %}
            <button type="submit" class="btn pull-right" name="submit" value="Create">Save Edits</button>
            <p>&nbsp;</p>
          </div>
    </div>
  </form>
  {% else %}
  <div class="well">
  <h1>You do not have the required permissions. Go away.</h1>
  </div>
  {% endif %}
  {% endblock %}

main/templates/main/edit_profile.html
{% extends "main/base.html" %}

{% block content %}
  {% if user.is_authenticated %}
  {% if form.errors %}
  <p class="warning">SOMETHING IS WRONG</p>
  <p class="warning">{{ form.errors }}</p>
  {% endif %}
  <form id="edit-profile" method="POST" action="{% url 'main:edit' user.userprofile.id %}">
    <div class="container">
      <div class="well">
        <h2 class="text-center">Edit Profile</h2>
        <div class="form-group">
            <div class="form-group">
              <label for="id_v_name">Name:</label>
              <input placeholder="Name" class="form-control" type="text" name="v_name" maxlength="64" required id="v_name" value="{{user.userprofile.v_name}}"/>
            </div>
            <div class="form-group">
              <label for="id_bio">Bio:</label>
              <textarea rows = 6 placeholder="Tell us about Yourself" class="form-control" name="bio" maxlength="1024" required id="id_bio">{{user.userprofile.bio}}</textarea>
            </div>
            {% csrf_token %}
            <button type="submit" class="btn pull-right" name="submit" value="Create">Save Edits</button>
            <p>&nbsp;</p>
          </div>
    </div>
  </form>
  {% else %}
  <div class="well">
  <h1>Dude, you gotta login to edit your profile, dude.</h1>
  </div>
  {% endif %}
  {% endblock %}

main/templates/main/game_overview.html
{% extends "main/base.html" %}
{% load main_extras %}
{% block content %}
<div class="container">
  {% if user.userprofile in game.players.all or game.game_master == user.userprofile %}
  <!-- user in game.players DO SOMETHING TO CHECK IF A USER IS IN THE GAME-->
    <div class="well">
      <h1 class="text-center display-1">{{game.name}}</h1>
      <div class="well overview">
        <h3>{{game.desc}}</h3>
        <h3>GM: {{game.game_master.v_name}}</h3>
        <h3>Ruleset: {{game.ruleset}}</h3>
        <h3>Rating: {{game.ESRB}}</h3>
        <h3>Location: {{game.location}}</h3>
        <h3>Players: {{game.int_current_players}}/{{game.max_players}} </h3>
        <h3>Encounters: {{game.num_encounters}} </h3>
        <h3>{{game.created_at}}</h3>
        {% if game.game_master == user.userprofile %}
          <a href="/main/edit_game/{{game.id}}" class="btn btn-primary">Edit Game</a>
        {% endif %}
      </div>
      {% if game.game_master == user.userprofile %}
        <div class="well">
          <h3>Manage Game:</h3>
          <div class="well overview">
            <h4>Manage Players:</h4>
            {% if game.players.all%}
              {% remove_player %}
            {% else %}
              <p>No players currently in game</p>
            {% endif %}
          </div>
          <br /><br />
          <div class="well overview">
            <h4>Pending Join Requests:</h4>
            {% if game.pending_players.all %}
              {% pending_chars %}
            {%else%}
              <p>No pending requests</p>
            {%endif%}
          </div>
          <div class="well overview">
            {% delete_game %}
          </div>
        </div>
      {% else %}
        <div class="well overview">
          <h3>Players</h3>
          {% for p in game.players.all %}
            <p>{{p.v_name}}</p>
          {%endfor%}
        </div>
      {%endif%}
    </div>
  {%else%}
    <!--DISPLAY LIMITED INFORMATION AND JOIN BUTTON-->
    <div class="well">
    <h1>{{game.name}}</h1>
    <h3>{{game.desc}}</h3>
    Would you like to join this game? {% join_game %}
    </div>
  {%endif%}
</div>
{%endblock%}

main/templates/main/index.html
{%extends 'main/base.html'%}
{% load main_extras %}

{% block content %}
{% if not games.empty %}
    <section class="game-list">
    {% for g in games %}
        <div class ="well col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1 col-lg-10 well col-md-10 col-sm-10 col-xs-10">
          <h3 class="title">{{ g.name }}</h3>
          <p>{{g.desc}}</p>
          <div class ="players">{{g.int_current_players}}/{{g.max_players}} </div>
          <div class="timestamp">{{g.created_at}}</div>
          <div>{{g.game_master.v_name}}</div>
          {% join_game %}
        </div>
        {% endfor %}
    </section>
    {% if games.paginator.num_pages > 1 %}
    <div class="well text-center col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1 col-lg-10 well col-md-10 col-sm-10 col-xs-10">
        <div class="pagination">
            <span class="step-links">
                {% if games.has_previous %}
                <a class="btn" href="?page=1">&laquo; first</a>
                <a class="btn" href="?page={{games.previous_page_number}}">previous</a>
                {% endif %}
                <span class="current">
                    Page {{games.number}} of {{games.paginator.num_pages}}.
                </span>
                {% if games.has_next %}
                <a class="btn" href="?page={{games.next_page_number}}">next</a>
                <a class="btn" href="?page={{games.paginator.num_pages}}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
    {% endif %}
{% else %}
<div class="well">
    <h1 class="no-games">THERE ARE NO GAMES</h1>
    <h3 class="no-games"> The world is empty and joyless</h3>
    <a href="/main/create" class="btn btn-default btn-lg">Start the first adventure</a>
</div>
{% endif %}
{% endblock %}

main/templates/main/profile.html
{%extends "main/base.html"%}
{% load main_extras %}

{%block content%}
<title> User Profile</title>
<div class="container">
  {% if user.is_authenticated %}
  <div class="well">
    <h1>{{ user.userprofile.v_name }}</h1>
    <div class="well">
    <h2>Your personal info</h2>
    <ul>
      <li> Username: {{user}} </li>
      <li> {{user.userprofile.bio}} </li>
      <li>Joined: {{user.userprofile.join_date}}</li>
      <a href="/main/profile/edit/{{user.userprofile.id}}" class="btn">Edit profile</a>
      {% delete_player %}
    </div>
      {% for c in user.userprofile.user_character_set.all %}
      <div class="well"><h3>{{c.name}}</h3><h4>{{c.bio}}</h4><h4>{{c.associated_game}}</h4>{% delete_character %}</div>
      {%endfor%}

    </ul>
        <div class="create_character">
          {% create_character %}
        </div>
  </div>
  {%else%}
  <div class="well">
    <h1>You must be logged in to see this page</h1>
    <a href="{%url 'login'%}" class="btn">Login</a>
  </div>
  {%endif%}
</div>
{%endblock%}

main/templates/main/register.html
{%extends "main/base.html" %}

  {%block content%}
    {% if registered %}
      <h3>You are account has been created</h3>
      <a href="/main/">Join a game</a><br/>
    {% else %}
      {% if form.errors %}
        <h1>There were errors</h1>
        <p class="warning">{{ form.errors }}</p>
      {% endif %}
    <form id="create-user" method="POST" action="/main/register/">
        <div class="container">
          <div class = "well">
            <h2 class="text-center">Create Account</h2>
            <div class = "form-group">
                <input placeholder="Name" class="form-control" type="text" name="v_name" maxlength="32" required id="id_v_name">
            </div>
            <div class="form-group">
              <input placeholder="Username" class="form-control" type="text" name="username" maxlength="150" required id="id_username">
              <!--<span class="helptext">Required. under 150 Characters. Letters, digits and @/./+/-/_ only.</span>-->
            </div>
            <div class = "form-group">
              <input placeholder="Password" class="form-control" type="password" name="password" required id="id_password"/>
            </div>
            {% csrf_token %}      
            <button type="submit" class="btn btn-primary pull-right" name="submit" value="Register">Create Account</button>
            <p>&nbsp;</p>
          </div>
        </div>
      </form>
    {% endif %}
  {%endblock%}