gamespace/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
  path("main/", include("main.urls")),
  path('accounts/', include('django.contrib.auth.urls')),
  path('admin/', admin.site.urls),
]

handler404 = 'main.views.handler404'
handler403 = 'main.views.handler403'

main/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
#add the view to urlpatterns
app_name= "main"
urlpatterns = [
  path("",views.listing, name = "game"),
  path("register/", views.register,name="register"),
  path("create/", views.CreateGame.as_view(),name="create"),
  path("profile/", views.Profile.as_view(),name="profile"),
  path("game_overview/<int:pk>/",views.GameOverview.as_view(),name="game_overview"),
  path("join_request/<int:pk>/", views.JoinRequest.as_view(),name="join_request"),
  path("pending_chars/<int:pk>/", views.Pending.as_view() ,name="pending_characters"),
  path("remove_player/<int:pk>/", views.Remove.as_view() ,name="remove_player"),
  path("edit_game/<int:pk>/", views.EditGame.as_view(), name="edit_game"),
  path("create_character/",views.CreateCharacter.as_view(),name="create_character"),
  path("profile/edit/<int:pk>/",views.EditProfile.as_view(),name="edit"),
  path("delete_game/<int:pk>/", views.DeleteGame.as_view() ,name="delete_game"),
  path("delete_player/<int:pk>/", views.DeletePlayer.as_view() ,name="delete_player"),
  path("delete_character/<int:pk>/",views.DeleteCharacter.as_view(),name="delete_character"),
]

main/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# this is where our databases are setup (I think)
# helpfull list of Fields https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.CharField


class UserProfile(models.Model):
    objects = models.Manager()

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    v_name = models.CharField(max_length=32)
    bio = models.CharField(max_length=512, default="A new adventurer ")
    join_date = models.DateTimeField("date joined", default=timezone.now)
    email = models.EmailField(max_length=254)
    picture = models.ImageField(
        upload_to=None, height_field=None, width_field=None, max_length=100)


    def get_bio(self):
        return self.bio

    def __str__(self):
        return self.v_name

    def update_profile(self, up):
      self.v_name = up.v_name
      self.bio = up.bio
      self.save()



class Game(models.Model):
    objects = models.Manager()

    game_master = models.ForeignKey(
        UserProfile, related_name="game_master", null=True, on_delete=models.CASCADE)

    created_at = models.DateTimeField("date created", default=timezone.now)
    name = models.CharField(max_length=64, default="A super cool adventure")
    desc = models.CharField(max_length=1024, default="")
    ruleset = models.CharField(max_length=64, default="")
    ESRB = models.CharField(max_length=16, default="Exactly 3 years old")
    location = models.CharField(max_length=256, default="SPACE")
    max_players = models.IntegerField(default=4)
    int_current_players = models.IntegerField(default=0)
    num_encounters = models.IntegerField(default=5)
    # who want's pictures for the games too?

    players = models.ManyToManyField(UserProfile, related_name="in_games")
    pending_players = models.ManyToManyField(
        UserProfile, related_name="pending_players")

    def get_desc(self):
        return self.desc

    def __str__(self):
        return self.name
    
    def update_game(self, game):
        self.name = game.name
        self.desc = game.desc
        self.ruleset = game.ruleset
        self.ESRB = game.ESRB
        self.location = game.location
        self.max_players = game.max_players
        self.num_encounters = game.num_encounters
        self.save()

    def is_equal(self, game):
        if not(self.name == game.name):
            return False
        if not(self.desc == game.desc):
            return False
        if not(self.ruleset == game.ruleset):
            return False
        if not(self.ESRB == game.ESRB):
            return False
        if not(self.location == game.location):
            return False
        if not(self.max_players == game.max_players):
            return False
        if not(self.num_encounters == game.num_encounters):
            return False

class Character(models.Model):
    objects = models.Manager()

    owner = models.ForeignKey(UserProfile, related_name="user_character_set",null=True, on_delete=models.CASCADE)
    associated_game = models.ForeignKey(Game,related_name="game_character_set",on_delete=models.CASCADE)
    name = models.CharField(max_length= 64)
    bio = models.CharField(max_length= 512)
    # when we get to uploading pdfs a fileField may be usefull
    characterSheet = models.ImageField(
        upload_to=None, height_field=None, width_field=None, max_length=100)
    hasButt = models.BooleanField(default=True)

    def update_character(self, character):
        self.name = character.name
        self.bio = character.bio
        self.save()

    def set_butt(self, bool):
      self.hasButt=bool

main/forms.py
from django import forms
from main.models import UserProfile, Game
from django.contrib.auth.models import User

#django authentication for username and password
class CreateUserForm(forms.ModelForm):
  #this formats the password to do the auto hide thing
  password = forms.CharField(widget=forms.PasswordInput())

  #the class meta provides the minimum for the form 
  class Meta:
    model = User
    #will add email in iteration 2 if we decide to have email enabled
    fields = ("username","password")

#form fields specific to out project
class CreateUserProfileForm(forms.ModelForm):
  class Meta:
    model = UserProfile
    fields = ("v_name",)

main/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic, View
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.contrib.auth import login, logout
from django.template import RequestContext
from django.utils import timezone
from django import template

from .models import UserProfile, Game, Character
from main.forms import CreateUserForm, CreateUserProfileForm

#----------------
# Main pages
#----------------

def listing(request):
  obj_list = Game.objects.order_by('-created_at')
  paginator = Paginator(obj_list,5)

  page = request.GET.get('page')
  games=paginator.get_page(page)
  return render(request,"main/index.html",{"games":games})

  
class Login(CreateView):
  template_name = "accounts/login.html"
  CreateView.model = UserProfile
  fields = '__all__'
  success_url="/main"


class Profile(TemplateView):
  template_name = "main/profile.html"


class GameOverview(generic.DetailView):
  model = Game
  context_object_name="game"
  template_name="main/game_overview.html"


#----------------
# Create views
#----------------
class CreateGame(CreateView):
  template_name = "main/create_game.html"
  CreateView.model = Game
  fields="name","desc","max_players","ruleset","ESRB","location","num_encounters"
  success_url="/main"
  def form_valid(self, form):
    game=form.save(commit=False)
    game.game_master = self.request.user.userprofile
    self.object=game
    self.object.save()
    return HttpResponseRedirect(self.get_success_url())

def register(request):
  context = RequestContext(request)
  registered = False
  if request.method=="POST":
    user_form = CreateUserForm(data=request.POST)
    profile_form = CreateUserProfileForm(data=request.POST)

    if user_form.is_valid() and profile_form.is_valid():
      user=user_form.save()

      #the set_password function hashes our password
      user.set_password(user.password)
      user.save()

      profile = profile_form.save(commit=False)
      profile.user = user
      profile.save()

      registered = True
      return HttpResponseRedirect("/accounts/login/",context)
  else:
    user_form = CreateUserForm()
    profile_form = CreateUserProfileForm()
    
  return render_to_response("main/register.html", {"user_form":user_form, "profile_form":profile_form,"registered":registered}, context)


#----------------
# Edit views
#----------------
class EditGame(UpdateView):
  template_name = "main/edit_game.html"
  model = Game
  fields="name","desc","max_players","ruleset","ESRB","location","num_encounters"

  def form_valid(self, form):
    if self.request.user.userprofile==self.object.game_master:
      game=form.save(commit=False)
      self.object.update_game(game)
      return HttpResponseRedirect("/main/game_overview/" + str(self.object.id))

class EditProfile(UpdateView):
  template_name = "main/edit_profile.html"
  model = UserProfile
  fields="v_name","bio",

  def form_valid(self,form):
    if self.request.user.userprofile==self.object:
      up=form.save(commit=False)
      self.object.update_profile(up)
      return HttpResponseRedirect("/main/profile/")



#class EditCharacter(UpdateView):
    

#----------------
# Tags
#----------------
class RequestView(generic.DetailView):
  template_name = "main/request.html"
  model = Game
  context_object_name = "game"
     
class Pending(UpdateView):
  template_name = "tags/pending_chars.html" # these are needed for form processing
  fields=["players",]
  model = Game
  def form_valid(self,form):
    state=self.request.POST.__getitem__("submit")
    if state=="Create":
      for p in self.request.POST.getlist("players"):
        u=UserProfile.objects.get(id=p)
        self.object.players.add(u)
        self.object.pending_players.remove(u)
        self.object.int_current_players+=1
        self.object.save()
    if state =="Destroy":
      for p in self.request.POST.getlist("players"):
        self.object.pending_players.remove(UserProfile.objects.get(id=p))
        self.object.save()
    return HttpResponseRedirect("/main/game_overview/" + str(self.object.id)) #this is how to redirect to same page

#handles removing user from game, inserted into game_overview
class Remove(UpdateView):
  template_name = "tags/remove_player.html" # these are needed for form processing
  fields=["players",]
  model = Game
  def form_valid(self,form):
    if (self.request.user.userprofile == self.object.game_master):
      for p in self.request.POST.getlist("players"):
        u=UserProfile.objects.get(id=p) # finds the user with the pending id
        self.object.players.remove(u) #removes that user from the game's players
        self.object.int_current_players-=1
        self.object.save()
      return HttpResponseRedirect("/main/game_overview/" + str(self.object.id)) #this is how to redirect to same page
    else:
      response = render_to_response("/error_codes/403.html")
      response.status_code = 403
      return response

class DeleteGame(DeleteView):
  template_name="tags/delete_game.html"
  fields=[]
  model = Game
  success_url="/main/"
  def form_valid(self,form):
    if (self.request.user.userprofile == self.object.game_master):
      self.object.delete()
      return HttpResponseRedirect(self.get_success_url())

class DeletePlayer(UpdateView):
  template_name="tags/delete_game.html"
  fields=[]
  model=UserProfile
  success_url="/main/"
  def form_valid(self,form):
      u = UserProfile.objects.get(id=self.request.user.id).user
      u.is_active=False
      u.delete()
      return HttpResponseRedirect(self.get_success_url())

class DeleteCharacter(DeleteView):
  template_name="tags/delete_character.html"
  fields=[]
  model = Character
  success_url="/main/profile/"
  def form_valid(self,form):
    if (self.request.user.userprofile == self.object.owner):
      self.object.delete()
      return HttpResponseRedirect(self.get_success_url())


class JoinRequest(UpdateView):
  template_name = "tags/request.html"
  model = Game
  fields=[]
  success_url="/main"
  def form_valid(self,form):

    game=self.object
    up=self.request.user.userprofile
    if up not in game.players.all():#guard
      game.pending_players.add(up)
      game.save()
    return HttpResponseRedirect(self.get_success_url())


class CreateCharacter(CreateView):
  template_name = "tags/create_character.html"
  fields=["name","bio","associated_game"]
  model = Character
  def form_valid(self,form):
    print("\n\nVALID\n\n")
    character=form.save(commit=False)
    character.owner = self.request.user.userprofile
    self.object=character
    self.object.save()
    return HttpResponseRedirect("/main/profile")
  def form_invalid(self,form):
    print("\n\nINVALID\n\n")
    for p in form:
      print(str(p))
      print("\n")
    return HttpResponseRedirect("/main/profile")

main/templates/tags/create_character.html
<form action="{% url 'main:create_character' %}" id="create_character" method="POST">
        <div class="well">
          <h2 class="text-center">Create Character</h2>
          <div class="form-group">
            <label for="id_name">Name</label>
            <input placeholder="Name" class="form-control" type="text" name="name" maxlength="64" required id="id_name">
          </div>
          <div class="form-group">
            <label for="id_bio">Bio</label>
            <textarea rows = 6 placeholder="bio" class="form-control" name="bio" maxlength="1024" id="id_bio"></textarea>
          </div>
          <div class="form-group">
            <!-- <label for="id_associated_game">Associated Game</label> -->
            <select name="associated_game" class="form-control" required id="associated_game">
              {% for g in user.userprofile.in_games.all %}
                <option value="{{g.id}}">{{g.name}}</option>
              {%endfor%}
            </select>
          </div>
          {% csrf_token %}
          <button type="submit" class="btn pull-right" name="submit" value="Create">Create Character</button>
          <p>&nbsp;</p>
        </div>
</form>

main/templates/tags/delete_character.html
<form action="{% url 'main:delete_character' c.id %}" id="delete-character" method="POST">
  {% csrf_token %}      
  <button type="submit" class=" btn-danger " name="delete" value="delete">Delete</button>
</form>

main/templates/tags/delete_game.html
{% if user.userprofile == game.game_master %}
<form action="{% url 'main:delete_game' game.id %}" id="delete-game" method="POST">
  {% csrf_token %}      
  <button type="submit" class=" btn-danger btn-lg" name="delete" value="delete">DELETE GAME</button>
</form>
{% endif %}

main/templates/tags/delete_player.html
<form action="{% url 'main:delete_player' user.userprofile.id %}" id="delete-player" method="POST">
  {% csrf_token %}      
  <button type="submit" class=" btn-danger pull-right" name="delete" value="delete">DELETE YOUR ACCOUNT?</button>
</form>

main/templates/tags/join_game.html
  {% if user.userprofile in g.players.all %}
  <br/>
    <a href="{% url 'main:game_overview' g.id %}" class ="btn btn-default btn-lg">View</a>
  {%elif g.game_master == user.userprofile%}
  <br/>
    <a href="{% url 'main:game_overview' g.id %}" class ="btn btn-default btn-lg">Manage</a>
  {% elif user.userprofile in g.pending_players.all %}
  <br/>
      <a class="btn btn-default btn-lg greyed-out" >Request Pending</a>
  {% elif user.is_authenticated %}
  <br/>
  <form action="{% url 'main:join_request' g.id %}" id="join-game" method="POST">
    {% csrf_token %}      
    <button type="submit" class="btn btn-default btn-lg" name="submit" value="Create">Join Game</button>
  </form>
  {% endif %}

main/templates/tags/pending_chars.html
<form action="{% url 'main:pending_characters' game.id %}" id="join-game" method="POST">
  {% for chara in game.pending_players.all %}
  <input type="checkbox" name = "players" value={{chara.id}}>
  {{chara.v_name}}
  <br/>
  {%endfor%}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary pull-right" name="submit" value="Create">Approve</button>
  <button type="submit" class="btn btn-primary pull-right" name="submit" value="Destroy">Deny</button>
  <p>&nbsp;</p>
</form>

main/templates/tags/remove_player.html
<form action="{% url 'main:remove_player' game.id %}" id="remove_player" method="POST">
  {% for chara in game.players.all %}
  <input type="checkbox" name="players" value={{chara.id}}>
  {{chara.v_name}}
  <br />
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary pull-right" name="submit" value="Destroy">Delete selected player(s)</button>
  <p>&nbsp;</p>
</form>